##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator (GitHub Pages)
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# SITE IDENTITY
title: "CLARENCE FITZROY BRYANT COLLEGE (CFBC)"
tagline: "Open access collection of texts, maps, and images"
description: "A digital collection on the history of Clarence Fitzroy Bryant College (CFBC)."
author: "Liburd Tavernier, Willa"

##########
# URLS (GitHub Pages deployment)
# Site published at: https://uzoamaka1900.github.io/Clarence-Fitzroy-Bryant-College-CFBC-/
url: "https://uzoamaka1900.github.io"
baseurl: "/Clarence-Fitzroy-Bryant-College-CFBC-"

# GitHub repository reference
repository: "uzoamaka1900/Clarence-Fitzroy-Bryant-College-CFBC-"
source-code: "https://github.com/uzoamaka1900/Clarence-Fitzroy-Bryant-College-CFBC-"

##########
# THEME / PLUGINS
remote_theme: collectionbuilder/collectionbuilder-gh
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

##########
# COLLECTION SETTINGS
# CSV (without .csv) in _data/ describing items
metadata: demo-metadata

collections:
  items:
    output: true

##########
# NAVIGATION
# Using CSV-based ECDA-style dropdown menus
navigation_source: "_data/config-nav.csv"

##########
# SEARCH
lunr_search: true

##########
# BRANDING
organization-name: "Clarence-Fitzroy-Bryant College (CFBC)"
organization-link: "https://uzoamaka1900.github.io/Clarence-Fitzroy-Bryant-College-CFBC-/"
organization-logo-banner: "/assets/img/cfbc-crest.png"
organization-logo-nav: "/assets/img/cfbc-crest.png"
logo_image: "/assets/img/cfbc-crest.png"

# Background for the title band
brand_images:
  title_background: "/assets/img/background.jpg"
  crest: "/assets/img/cfbc-crest.png"              # crest path (same as above)

# Feature flags (handy if you toggle custom header/title later)
features:
  use_custom_header: true
  use_title_background: true

##########
# FOOTER
footer_credit: >
  This project was created using <a href="https://collectionbuilder.github.io/">CollectionBuilder-GH</a>.
  Content © Clarence-Fitzroy-Bryant College (CFBC).

##########
# BUILD SETTINGS
exclude:
  - docs/
  - Rakefile
  - README.md
  - LICENSE
  - CITATION.cff
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md

sass:
  style: compressed
