##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator (GitHub Pages)
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# SITE IDENTITY
title: "Clarence-Fitzroy-Bryant-College-(CFBC)"
tagline: "Open access collection of texts, maps, and images"
description: "A digital collection on the history of Clarence Fitzroy Bryant College (CFBC_."
author: "Liburd Tavernier, Willa "

##########
# URLS (set these to match your GitHub Pages setup)
# If this is a *project* site: url = https://<user>.github.io  AND baseurl = /<repo>
# If this is a *user/org* site: url = https://<user>.github.io AND baseurl = ""
url: "https://uzoamaka1900.github.io/Clarence-Fitzroy-Bryant-College-CFBC-/"
baseurl: "/your-repo"

# Repo reference (helps some links/tools)
repository: https://uzoamaka1900.github.io/Clarence-Fitzroy-Bryant-College-CFBC-/your-username/your-repo
source-code: https://uzoamaka1900.github.io/Clarence-Fitzroy-Bryant-College-CFBC-/

##########
# THEME / PLUGINS
remote_theme: collectionbuilder/collectionbuilder-gh
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

##########
# COLLECTION SETTINGS
# Use your metadata CSV file name (without .csv) located in _data/
metadata: demo-metadata

collections:
  items:
    output: true

##########
# NAVIGATION
# We’re using the CSV you edited for the ECDA-style dropdowns
navigation_source: _data/config-nav.csv

##########
# SEARCH
lunr_search: true

##########
# BRANDING (optional; add your logo paths if you have them)
# organization-name: "Clarence-Fitzroy-Bryant-College-(CFBC)"
# organization-link: https://uzoamaka1900.github.io/Clarence-Fitzroy-Bryant-College-CFBC-/
# organization-logo-banner: /objects/ST.%20KITTS%20AND%20NEVIS%20IN%201988.png
# organization-logo-nav: /assets/img/logo-nav.png
# logo_image: /objects/ST.%20KITTS%20AND%20NEVIS%20IN%201988.png

##########
# FOOTER
footer_credit: >
  This project was created using <a href="https://collectionbuilder.github.io/">CollectionBuilder-GH</a>. Content © Your Organization.

##########
# BUILD SETTINGS
exclude:
  - docs/
  - Rakefile
  - README.md
  - LICENSE
  - CITATION.cff
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md

sass:
  style: compressed
